import React from 'react';
import {
  FlaskRound as Flask,
  Brain,
  Lock,
  Zap,
  ExternalLink,
} from 'lucide-react';

/**
 * <Research />
 * ByteBrain – Research & Products section
 * ──────────────────────────────────────
 * All project names, descriptions, and links are the *real* (or anonymised) initiatives
 * currently in flight at ByteBrain LLC as of June 2025.
 *
 * To add/adjust projects, simply update the `projects` array below.
 */

const Research = () => {
  const projects = [
    {
      icon: Flask,
      title: 'MEDRAIL™',
      subtitle: 'Multi‑Agent Clinical‑Trial Copilot',
      description:
        'Patent‑pending simulation platform that uses collaborative RL agents to de‑risk study design, flag safety issues, and optimise recruitment in silico.',
      status: 'Patent Pending',
      tags: ['Reinforcement Learning', 'Clinical AI', 'Simulation'],
      externalLink: '#',
    },
    {
      icon: Brain,
      title: 'RAG‑as‑a‑Service',
      subtitle: 'Enterprise‑Grade Knowledge Retrieval',
      description:
        'API‑first service that indexes PDFs, sitemaps & databases into isolated vector spaces, delivering <300 ms contextual answers at 100k‑document scale.',
      status: 'In Production',
      tags: ['RAG', 'Vector Search', 'Multi‑Tenant'],
      externalLink: 'https://api.thebytebrain.com',
    },
    {
      icon: Zap,
      title: 'MediaOps Agent',
      subtitle: 'Automated Ad Planning & Reporting',
      description:
        'Connects to ad‑network APIs, drafts briefs, dashboards & campaign plans—cutting analyst hours by ~70 % for leading agencies.',
      status: 'Private Beta',
      tags: ['Agentic AI', 'Advertising', 'Automation'],
      externalLink: '#',
    },
    {
      icon: Lock,
      title: 'AI Compliance Benchmark',
      subtitle: 'Stress‑Testing KYC & AML Suites',
      description:
        'Open evaluation suite that pits leading compliance APIs against synthetic & real forgeries generated by state‑of‑the‑art LLM and diffusion models.',
      status: 'Research Complete',
      tags: ['Compliance', 'Security', 'Benchmark'],
      externalLink: '#',
    },
  ];

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Patent Pending':
        return 'bg-yellow-100 text-yellow-800 border-yellow-200';
      case 'In Production':
        return 'bg-green-100 text-green-800 border-green-200';
      case 'Research Complete':
        return 'bg-blue-100 text-blue-800 border-blue-200';
      case 'Private Beta':
        return 'bg-purple-100 text-purple-800 border-purple-200';
      default:
        return 'bg-gray-100 text-gray-800 border-gray-200';
    }
  };

  return (
    <section id="research" className="py-20 bg-[#FAFAFA]">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Heading */}
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold text-[#2D2868] mb-4">
            Research &amp; Products
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Pioneering AI research, shipped as real‑world solutions
          </p>
        </div>

        {/* Project grid */}
        <div className="grid lg:grid-cols-2 gap-8 mb-12">
          {projects.map((project, index) => {
            const Icon = project.icon;
            return (
              <div
                key={index}
                className="bg-white rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 overflow-hidden group"
              >
                <div className="p-8">
                  {/* Header */}
                  <div className="flex items-start justify-between mb-6">
                    <div className="flex items-center">
                      <div className="p-3 bg-gradient-to-br from-[#00C9B1] to-[#2D2868] rounded-xl mr-4">
                        <Icon className="h-6 w-6 text-white" />
                      </div>
                      <div>
                        <h3 className="text-xl font-bold text-[#2D2868]">
                          {project.title}
                        </h3>
                        <p className="text-[#00C9B1] font-medium text-sm">
                          {project.subtitle}
                        </p>
                      </div>
                    </div>
                    <span
                      className={`px-3 py-1 rounded-full text-xs font-medium border ${getStatusColor(
                        project.status,
                      )}`}
                    >
                      {project.status}
                    </span>
                  </div>

                  {/* Body */}
                  <p className="text-gray-600 mb-6 leading-relaxed">
                    {project.description}
                  </p>

                  {/* Tags */}
                  <div className="flex flex-wrap gap-2 mb-6">
                    {project.tags.map((tag, tagIndex) => (
                      <span
                        key={tagIndex}
                        className="bg-gray-100 text-gray-700 px-3 py-1 rounded-full text-xs font-medium"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>

                  {/* External Link */}
                  {project.externalLink !== '#' && (
                    <div className="flex justify-end">
                      <a
                        href={project.externalLink}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center text-gray-500 hover:text-[#2D2868] transition-colors"
                      >
                        <ExternalLink className="h-4 w-4" />
                      </a>
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>

        {/* Highlighted Initiative */}
        <div className="bg-gradient-to-r from-[#2D2868] to-[#4C46A0] rounded-2xl p-8 text-white">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-2xl font-bold mb-4">
                Autonomous Compliance Document Agent
              </h3>
              <p className="text-white/90 mb-4 max-w-2xl">
                Our latest research prototype continuously monitors regulatory updates
                and drafts the necessary SOPs &amp; evidence packages—keeping enterprises
                audit‑ready with near‑zero manual effort.
              </p>
              <div className="flex flex-wrap gap-2">
                <span className="bg-white/20 text-white px-3 py-1 rounded-full text-sm">
                  Regulatory AI
                </span>
                <span className="bg-white/20 text-white px-3 py-1 rounded-full text-sm">
                  Autonomous Agents
                </span>
                <span className="bg-white/20 text-white px-3 py-1 rounded-full text-sm">
                  Document Automation
                </span>
              </div>
            </div>
            <div className="hidden lg:block">
              <div className="w-32 h-32 bg-white/10 rounded-full flex items-center justify-center">
                <Brain className="h-16 w-16 text-[#00C9B1]" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Research;